{
 "title": "Defcon",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Defcon Value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "defcon_level{instance=\"web.speedport.ip:80\"}"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "defcon_changed{instance=\"web.speedport.ip:80\"}",
     "legendFormat": "Last Change"
    }
   ]
  },
  {
   "title": "Exporter Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "defcon_error{instance=\"web.speedport.ip:80\"}",
     "legendFormat": "Code {{code}}"
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "defcon_info{instance=\"web.speedport.ip:80\"}"
    }
   ]
  }
 ]
}